-- Colori tag trascritti dalla configurazione Zoho prima della dismissione.
-- Aggiorna solo i tag Lead già importati; non crea record.
update public.tag set colore = '#D9A441' where modulo = 'lead' and lower(nome) = lower('RICHIAMARE IN FUTURO');
update public.tag set colore = '#C0392B' where modulo = 'lead' and lower(nome) = lower('NEGATIVO');
update public.tag set colore = '#E8902E' where modulo = 'lead' and lower(nome) = lower('NON RISPONDE - SEGRETERIA');
update public.tag set colore = '#5B7891' where modulo = 'lead' and lower(nome) = lower('OLD');
update public.tag set colore = '#3DA89A' where modulo = 'lead' and lower(nome) = lower('RIGENERATO');
update public.tag set colore = '#E0457B' where modulo = 'lead' and lower(nome) = lower('NUMERO ERRATO');
update public.tag set colore = '#6FBF73' where modulo = 'lead' and lower(nome) = lower('Non risponde');
update public.tag set colore = '#6FBF73' where modulo = 'lead' and lower(nome) = lower('Richiamare');
update public.tag set colore = '#3DA89A' where modulo = 'lead' and lower(nome) = lower('richiamare tra mesi');
update public.tag set colore = '#F2D24A' where modulo = 'lead' and lower(nome) = lower('In attesa');
update public.tag set colore = '#C8A2E0' where modulo = 'lead' and lower(nome) = lower('installatore');
update public.tag set colore = '#5B7891' where modulo = 'lead' and lower(nome) = lower('Ricliccato');
update public.tag set colore = '#D9A441' where modulo = 'lead' and lower(nome) = lower('in attesa bollette');
update public.tag set colore = '#8A8D93' where modulo = 'lead' and lower(nome) = lower('Non risponde piu`');
update public.tag set colore = '#D9A441' where modulo = 'lead' and lower(nome) = lower('Fake');
update public.tag set colore = '#A8B84A' where modulo = 'lead' and lower(nome) = lower('Inviato Preventivo');
update public.tag set colore = '#6FBF73' where modulo = 'lead' and lower(nome) = lower('PERDITA DI TEMPO');
update public.tag set colore = '#F2D24A' where modulo = 'lead' and lower(nome) = lower('Posticipato');
update public.tag set colore = '#E58A8A' where modulo = 'lead' and lower(nome) = lower('non contattato');
update public.tag set colore = '#8E96E6' where modulo = 'lead' and lower(nome) = lower('Inviare preventivo');
update public.tag set colore = '#8E96E6' where modulo = 'lead' and lower(nome) = lower('Fuori target');
update public.tag set colore = '#E68FB0' where modulo = 'lead' and lower(nome) = lower('Fissata Call');
update public.tag set colore = '#5B9BD5' where modulo = 'lead' and lower(nome) = lower('Trattativa');
update public.tag set colore = '#D9A441' where modulo = 'lead' and lower(nome) = lower('collaborazione');
update public.tag set colore = '#D9A441' where modulo = 'lead' and lower(nome) = lower('Capannone per CER');
update public.tag set colore = '#E8902E' where modulo = 'lead' and lower(nome) = lower('Sopralluogo fatto');
update public.tag set colore = '#E8902E' where modulo = 'lead' and lower(nome) = lower('solo per informazione');
update public.tag set colore = '#C8A2E0' where modulo = 'lead' and lower(nome) = lower('Fissato incontro');
update public.tag set colore = '#8A8D93' where modulo = 'lead' and lower(nome) = lower('PRATICHE ENEL');
update public.tag set colore = '#E8902E' where modulo = 'lead' and lower(nome) = lower('non interessato');
update public.tag set colore = '#C8A2E0' where modulo = 'lead' and lower(nome) = lower('CONSULENTE');
update public.tag set colore = '#5B9BD5' where modulo = 'lead' and lower(nome) = lower('Inviato Prospetto');
update public.tag set colore = '#5B9BD5' where modulo = 'lead' and lower(nome) = lower('Fissato sopralluogo');
update public.tag set colore = '#D9A441' where modulo = 'lead' and lower(nome) = lower('In ristrutturazione');
update public.tag set colore = '#A8B84A' where modulo = 'lead' and lower(nome) = lower('Impianto industriale');
update public.tag set colore = '#8E96E6' where modulo = 'lead' and lower(nome) = lower('ATTENZIONARE');
update public.tag set colore = '#A8B84A' where modulo = 'lead' and lower(nome) = lower('attendo essere ricontatta');
update public.tag set colore = '#5B7891' where modulo = 'lead' and lower(nome) = lower('Inviata offerta PNNR');
update public.tag set colore = '#3DA89A' where modulo = 'lead' and lower(nome) = lower('Senza numero');
update public.tag set colore = '#E58A8A' where modulo = 'lead' and lower(nome) = lower('Fissare sopralluogo');
update public.tag set colore = '#9BD675' where modulo = 'lead' and lower(nome) = lower('perso');
update public.tag set colore = '#E58A8A' where modulo = 'lead' and lower(nome) = lower('Fuori Raggio Agente');
update public.tag set colore = '#8A8D93' where modulo = 'lead' and lower(nome) = lower('Cantalupo');
update public.tag set colore = '#E58A8A' where modulo = 'lead' and lower(nome) = lower('doppione');
update public.tag set colore = '#C8A2E0' where modulo = 'lead' and lower(nome) = lower('conto termico');
update public.tag set colore = '#5B9BD5' where modulo = 'lead' and lower(nome) = lower('in attesa doc');
update public.tag set colore = '#E8902E' where modulo = 'lead' and lower(nome) = lower('tempo perso');
update public.tag set colore = '#F2D24A' where modulo = 'lead' and lower(nome) = lower('in corso');
update public.tag set colore = '#8A8D93' where modulo = 'lead' and lower(nome) = lower('MASE');
update public.tag set colore = '#5B7891' where modulo = 'lead' and lower(nome) = lower('rifiutato');
update public.tag set colore = '#A8B84A' where modulo = 'lead' and lower(nome) = lower('Vincenzo Sasso');
update public.tag set colore = '#A8B84A' where modulo = 'lead' and lower(nome) = lower('vedi note');
update public.tag set colore = '#C8A2E0' where modulo = 'lead' and lower(nome) = lower('DE Paola');
update public.tag set colore = '#E58A8A' where modulo = 'lead' and lower(nome) = lower('non più interessata');
update public.tag set colore = '#8B2E3F' where modulo = 'lead' and lower(nome) = lower('Tasso zero IRFIS');
update public.tag set colore = '#F2D24A' where modulo = 'lead' and lower(nome) = lower('NUOVO CONTRATTO');
