-- Replicates Zoho Clienti export columns from Clienti_2026_07_07.csv.
-- Existing CRM technical columns are preserved; Zoho timestamps are stored separately.

do $$
declare
  field record;
begin
  for field in
    select * from (values
      ('zoho_record_id', 'text', 'ID record'),
      ('clienti_proprietario_zoho_id', 'text', 'Clienti Proprietario.id'),
      ('clienti_proprietario', 'text', 'Clienti Proprietario'),
      ('origine_lead', 'text', 'Origine Lead'),
      ('nome', 'text', 'Nome'),
      ('cognome', 'text', 'Cognome'),
      ('nome_clienti', 'text', 'Clienti Name'),
      ('email', 'text', 'E-mail'),
      ('altro_telefono', 'text', 'Altro telefono'),
      ('cellulare', 'text', 'Cellulare'),
      ('creato_da_zoho_id', 'text', 'Creato da.id'),
      ('creato_da', 'text', 'Creato da'),
      ('modificato_da_zoho_id', 'text', 'Modificato da.id'),
      ('modificato_da', 'text', 'Modificato da'),
      ('ora_creazione', 'timestamp with time zone', 'Ora creazione'),
      ('ora_modifica', 'timestamp with time zone', 'Ora modifica'),
      ('saluti', 'text', 'Saluti'),
      ('e_mail_secondaria', 'text', 'E-mail secondaria'),
      ('ora_ultima_attivita', 'timestamp with time zone', 'Ora ultima attività'),
      ('via_indirizzo_postale', 'text', 'Via indirizzo postale'),
      ('citta_indirizzo_postale', 'text', 'Città indirizzo postale'),
      ('provincia_indirizzo_postale', 'text', 'Provincia indirizzo postale'),
      ('codice_postale_indirizzo', 'text', 'Codice postale indirizzo'),
      ('descrizione', 'text', 'Descrizione'),
      ('tag', 'text', 'Tag'),
      ('modalita_iscrizione_annullata', 'text', 'Modalità iscrizione annullata'),
      ('ora_iscrizione_annullata', 'timestamp with time zone', 'Ora  iscrizione annullata'),
      ('zoho_modified_at', 'timestamp with time zone', 'Orario del registro delle modifiche'),
      ('locked', 'boolean', 'Locked'),
      ('ora_ultimo_arricchimento', 'timestamp with time zone', 'Ora dell’ultimo arricchimento'),
      ('stato_arricchito', 'text', 'Stato arricchito'),
      ('stato', 'text', 'Stato'),
      ('visita_piu_recente', 'timestamp with time zone', 'Visita più recente'),
      ('prima_pagina_visitata', 'text', 'Prima pagina visitata'),
      ('tempo_medio_impiegato_minuti', 'numeric', 'Tempo medio impiegato (minuti)'),
      ('numero_di_chat', 'numeric', 'Numero di chat'),
      ('relatore', 'text', 'Relatore'),
      ('punteggio_visitatore', 'numeric', 'Punteggio visitatore'),
      ('prima_visita', 'timestamp with time zone', 'Prima visita'),
      ('giorni_visitati', 'numeric', 'Giorni visitati'),
      ('cod_inverter', 'text', 'COD. INVERTER'),
      ('cod_moduli', 'text', 'COD- MODULI'),
      ('cod_storage', 'text', 'COD. STORAGE'),
      ('disponibilita_magazzino', 'text', 'DISPONIBILITA'' MAGAZZINO'),
      ('installatore_zoho_id', 'text', 'Installatore.id'),
      ('installatore', 'text', 'Installatore'),
      ('nr_inverter', 'numeric', 'Nr. Inverter'),
      ('nr_moduli', 'numeric', 'Nr. Moduli'),
      ('potenza_moduli_wp', 'numeric', 'Potenza Moduli (Wp)'),
      ('nr_batterie', 'numeric', 'Nr. Batterie'),
      ('capacita_batterie', 'text', 'Capacità Batterie'),
      ('totale_storage', 'text', 'Totale Storage'),
      ('tot_potenza_dc', 'numeric', 'Tot Potenza DC'),
      ('potenza_inverter', 'numeric', 'Potenza Inverter'),
      ('modalita_di_pagamento', 'text', 'Modalità di Pagamento'),
      ('tot_potenza_ac_kw', 'numeric', 'Tot Potenza AC (KW)'),
      ('n_1_tranche', 'text', '1° Tranche'),
      ('importo_contrattuale', 'numeric', 'Importo Contrattuale'),
      ('bonifico_parziale', 'text', 'Bonifico Parziale'),
      ('importo_finanziamento', 'numeric', 'Importo Finanziamento'),
      ('n_2tranche', 'text', '2°Tranche'),
      ('saldo', 'numeric', 'Saldo'),
      ('stratigrafia_superficie_di_installazione', 'text', 'Stratigrafia superficie di installazione'),
      ('note', 'text', 'Note'),
      ('c_o_magazzino_installatore', 'text', 'C/o magazzino installatore'),
      ('indirizzo_di_ritiro_merce', 'text', 'Indirizzo di ritiro merce'),
      ('merce_ordinata_e_da_ritirare', 'text', 'Merce ordinata e da ritirare'),
      ('c_o_cantiere_del_cliente', 'text', 'C/o cantiere del cliente'),
      ('altri_materiali', 'text', 'Altri materiali'),
      ('importi_extra', 'text', 'Importi extra'),
      ('assistenza', 'text', 'Assistenza'),
      ('data_installazione_ultimata', 'timestamp with time zone', 'Data installazione ultimata'),
      ('note_ufficio', 'text', 'Note ufficio'),
      ('social_lead_id', 'text', 'Social Lead ID'),
      ('inserimento_pratica_gse', 'text', 'Inserimento pratica GSE'),
      ('iva_reverse_charge', 'boolean', 'Iva Reverse charge'),
      ('iva', 'numeric', 'IVA'),
      ('n_rate_e_importo_rata', 'numeric', 'N. rate e importo rata'),
      ('data_ammissibilita', 'timestamp with time zone', 'Data ammissibilità'),
      ('data_sopralluogo', 'timestamp with time zone', 'Data sopralluogo'),
      ('corrispettivo_pagato', 'boolean', 'Corrispettivo pagato'),
      ('mappa_catastale', 'text', 'Mappa catastale'),
      ('regolamento_di_esecizio', 'text', 'Regolamento di esecizio'),
      ('attestato_terna', 'text', 'Attestato Terna'),
      ('codice_contratto_pnrr', 'text', 'Codice contratto PNRR'),
      ('data_conferma_iter_e_distribuzione', 'timestamp with time zone', 'Data conferma Iter E-distribuzione'),
      ('notifica_pred_reg_esercizio', 'boolean', 'Notifica pred. reg. esercizio'),
      ('disponibilita_fine_lavori', 'boolean', 'Disponibilità Fine lavori'),
      ('tica', 'text', 'Tica'),
      ('stato_tica', 'text', 'Stato TICA'),
      ('importo_da_listino', 'numeric', 'Importo da Listino'),
      ('inserimento_pratica_e_distribuzione', 'text', 'Inserimento pratica E-Distribuzione'),
      ('impianto_in_edilizia_libera', 'boolean', 'Impianto in edilizia libera'),
      ('area_vincolata', 'boolean', 'Area vincolata'),
      ('potenza_nominale_superiore_20kw', 'text', '>20kW Pot. Nom.'),
      ('pod', 'text', 'POD'),
      ('zona', 'text', 'Zona'),
      ('stato_sollecito', 'text', 'Stato Sollecito'),
      ('tipo_ctr', 'text', 'TIPO CTR'),
      ('iban', 'text', 'IBAN'),
      ('finanziamento_approvato', 'boolean', 'Finanziamento approvato'),
      ('verifica_documentale', 'boolean', 'Verifica documentale'),
      ('layout_verificato', 'boolean', 'Layout verificato'),
      ('scheda_enea', 'text', 'Scheda ENEA'),
      ('note_pagamenti', 'text', 'Note pagamenti'),
      ('codice_rintracciabilita', 'text', 'Codice rintracciabilità'),
      ('stato_provvigione', 'text', 'Stato Provvigione.'),
      ('data_scadenza_tica', 'timestamp with time zone', 'Data scadenza TICA'),
      ('importo_tica', 'numeric', 'Importo TICA'),
      ('impianto_attivo', 'boolean', 'Impianto Attivo'),
      ('data_appuntamento_allaccio', 'timestamp with time zone', 'Data appuntamento allaccio'),
      ('tipologia', 'text', 'Tipologia'),
      ('retrofit', 'text', 'Retrofit'),
      ('data_interlocutorio', 'timestamp with time zone', 'Data interlocutorio'),
      ('eps', 'text', 'EPS'),
      ('note_provvigioni', 'text', 'Note Provvigioni'),
      ('stato_sopralluogo', 'text', 'Stato sopralluogo'),
      ('data_affidamento_sopralluogo', 'timestamp with time zone', 'Data affidamento sopralluogo'),
      ('data_iter_enel_concluso', 'timestamp with time zone', 'Data iter Enel Concluso'),
      ('messaggio_di_benvenuto', 'boolean', 'Messaggio di benvenuto'),
      ('messaggio_prog_preliminare', 'boolean', 'Messaggio prog. preliminare'),
      ('messaggio_ordine_merce', 'boolean', 'Messaggio ordine merce'),
      ('messaggio_in_esecuzione', 'boolean', 'Messaggio in esecuzione'),
      ('telefonata_post_installazione', 'boolean', 'Telefonata post installazione'),
      ('codice_fiscale', 'text', 'Codice fiscale'),
      ('messaggio_fattura', 'boolean', 'Messaggio Fattura'),
      ('data_click', 'timestamp with time zone', 'Data Click'),
      ('mod_pagamento_ct3_0', 'text', 'MOD. PAGAMENTO CT3.0'),
      ('intervento_2', 'text', 'Intervento 2'),
      ('intervento_1', 'text', 'Intervento 1'),
      ('fattura2', 'text', 'Fattura2'),
      ('fattura1', 'text', 'Fattura 1'),
      ('sconto_combo', 'numeric', 'Sconto COMBO'),
      ('bonifico2', 'text', 'Bonifico2'),
      ('bonifico1', 'text', 'Bonifico1'),
      ('st300', 'text', 'ST300'),
      ('scaldacqua_pdc', 'text', 'Scaldacqua PDC'),
      ('pdc_idronica', 'text', 'PDC idronica'),
      ('stf', 'text', 'STF'),
      ('accessori', 'text', 'Accessori'),
      ('litri_accumulo', 'numeric', 'Litri Accumulo'),
      ('n_collettori', 'numeric', 'N. Collettori'),
      ('bonificopdc', 'text', 'BonificoPDC'),
      ('p_d_c_idronica', 'text', 'P D C idronica'),
      ('fatturapdc', 'text', 'FatturaPDC'),
      ('incentivoatteso', 'numeric', 'IncentivoAtteso'),
      ('di_cui_ct3', 'numeric', 'di cui CT3'),
      ('tot_contratto', 'numeric', 'Tot Contratto'),
      ('di_cui_ftv', 'numeric', 'di cui FTV'),
      ('codice_inv_batt', 'text', 'Codice inv. batt.'),
      ('codice_ordine_sonepar', 'text', 'Codice  ordine Sonepar'),
      ('foglio', 'text', 'Foglio'),
      ('cer', 'text', 'CER'),
      ('sub', 'text', 'Sub'),
      ('particella', 'text', 'Particella'),
      ('tipo_di_tensione', 'text', 'TIPO DI TENSIONE'),
      ('nome_intestatario_utenza_elettrica', 'text', 'NOME - INTESTATARIO UTENZA ELETTRICA'),
      ('e_mail_enel_gaudi', 'text', 'E-mail Enel/Gaudi'),
      ('cognome_intestatario_utenza_elettrica', 'text', 'COGNOME - INTESTATARIO UTENZA ELETTRICA'),
      ('titolarita_impianto', 'text', 'TITOLARITA'' IMPIANTO'),
      ('desidera_installare_impianto_su', 'text', 'DESIDERA INSTALLARE L''IMPIANTO SU'),
      ('tipologia_proprietario', 'text', 'TIPOLOGIA PROPRIETARIO'),
      ('potenza_sistema_di_accumulo', 'numeric', 'POTENZA SISTEMA DI ACCUMULO')
    ) as v(column_name, column_type, zoho_label)
  loop
    execute format('alter table public.clienti add column if not exists %I %s', field.column_name, field.column_type);
  end loop;
end $$;

create unique index if not exists clienti_zoho_record_id_uidx
  on public.clienti (zoho_record_id)
  where zoho_record_id is not null;

create index if not exists clienti_stato_idx on public.clienti (stato);
create index if not exists clienti_sede_idx on public.clienti (sede);
create index if not exists clienti_ora_modifica_idx on public.clienti (ora_modifica desc);
